#!/bin/bash

echo "Setting up hospital manager accounts..."
echo ""
echo "This script will create two manager accounts:"
echo "  1. manager.spital1 (Password: SP1a4) - for Piatra-Neamț hospital"
echo "  2. manager.spital2 (Password: BH2x9) - for Buhuși hospital"
echo ""
echo "To run this setup:"
echo ""
echo "1. Open your browser and go to your application"
echo "2. Make sure you're logged in as admin"
echo "3. Use the admin panel to create new users with these details:"
echo ""
echo "=== MANAGER 1 ==="
echo "Name: Manager Spitalul Județean de Urgență Piatra-Neamț"
echo "Username: manager.spital1"
echo "Password: SP1a4"
echo "Role: manager"
echo "Hospital: spital1"
echo "Type: medic"
echo ""
echo "=== MANAGER 2 ==="
echo "Name: Manager Spitalul Prof. Dr. Eduard Apetrei Buhuși"
echo "Username: manager.spital2"
echo "Password: BH2x9"
echo "Role: manager"
echo "Hospital: spital2"
echo "Type: medic"
echo ""
echo "After creating these users, each manager will only be able to see their own hospital!"